version: 2.1

jobs:
  save_inventory:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - ./inventory

  print_inventory:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: cat ./inventory

workflows:
  my_workflow:
    jobs:
      - save_inventory
      - print_inventory:
          requires:
            - save_inventory
